# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Restaurant.create(name: 'The GoGo Grill', cuisine: 'Vegetarian', location: '1 Broadway, New York, NY 10004', img_url: "gogo grill.jpg")
    Item.create(name: "The Battery Burger", price: 7,restaurant_id: 1)
    Item.create(name: "The Garibaldi", price: 7,restaurant_id: 1)
    Item.create(name: "The Metropolitan", price: 6,restaurant_id: 1)
Restaurant.create(name: 'Suspenders', cuisine: 'Comfort Food', location: '108 Greenwich St, New York, NY 10006', img_url: "suspenders-food.jpg")
    Item.create(name: "BBQ Pulled Pork", price: 12,restaurant_id: 2)
    Item.create(name: "Suspenders Burger", price: 12,restaurant_id: 2)
    Item.create(name: "Wall Street Burger", price: 16,restaurant_id: 2)
Restaurant.create(name: 'BlackTail', cuisine: 'Cuban', location: '22 Battery Pl, New York, NY 10004', img_url: "blacktail-food.jpg")
    Item.create(name: "Sugarcane Gulf Shrimp", price: 16,restaurant_id: 3)
    Item.create(name: "Grilled Skirt Steak", price: 29,restaurant_id: 3)
    Item.create(name: "BlackTail Bruger & Fries", price: 24,restaurant_id: 3)
Restaurant.create(name: 'Balthazar', cuisine: 'French', location: '80 Spring St, New York, NY 10012', img_url: "balthazar-food.jpg")
    Item.create(name: "Steak Au Poivre", price: 45,restaurant_id: 4)
    Item.create(name: "Steak Frites", price: 39,restaurant_id: 4)
    Item.create(name: "Grilled Lamb T-Bones", price: 42,restaurant_id: 4)
Restaurant.create(name: 'Adriennes Pizzabar', cuisine: 'Pizza', location: '54 Stone St, New York, NY 10004', img_url: "Adrienne's Pizzabar.jpg")
    Item.create(name: "Old Fashioned Pizza", price: 23,restaurant_id: 5)
    Item.create(name: "Penne Chicken Parmesan", price: 19,restaurant_id: 5)
    Item.create(name: "Margherita", price: 17,restaurant_id: 5)
Restaurant.create(name: 'Naya', cuisine: 'Lebanese', location: 'One New York Plz, New York, NY 10004', img_url: "Naya.jpg")
    Item.create(name: "Chicken Shawarma", price: 8,restaurant_id: 6)
    Item.create(name: "Falafel", price: 7,restaurant_id: 6)
    Item.create(name: "Beef Shawarma", price: 8,restaurant_id: 6)
Restaurant.create(name: 'Ramen Ramen', cuisine: 'Ramen', location: '9 Broadway, New York, NY 10004', img_url: "Ramen Ramen.jpg")
    Item.create(name: "Tonkotsu", price: 9,restaurant_id: 7)
    Item.create(name: "Miso", price: 9,restaurant_id: 7)
    Item.create(name: "Shoyu", price: 9,restaurant_id: 7)
Restaurant.create(name: 'Dig Inn', cuisine: 'American', location: '80 Broad St, New York, NY 10004', img_url: "Dig Inn.jpg")
    Item.create(name: "Farmer's Favorite Marketbowl", price: 9,restaurant_id: 8)
    Item.create(name: "Charred Chicken Marketbowl", price: 11,restaurant_id: 8)
    Item.create(name: "Grilled Organic Tofu Marketbowl Vegan", price: 10,restaurant_id: 8)
Restaurant.create(name: 'Broadstone Bar & Kitchen', cuisine: 'American', location: '88 Broad St, New York, NY 10004', img_url: "Broadstone Bar & Kitchen.jpg")
    Item.create(name: "Light Seared Salmon", price: 25,restaurant_id: 9)
    Item.create(name: "Steak au Poivre", price: 30,restaurant_id: 9)
    Item.create(name: "Lobster Ravioli", price: 20,restaurant_id: 9)
Restaurant.create(name: 'Luckyim Thai', cuisine: 'Thai', location: '10 Hanover Sq, New York, NY 10005', img_url: "Luckyim Thai.jpg")
    Item.create(name: "Basil over rice", price: 7,restaurant_id: 10)
    Item.create(name: "Spicy fried rice", price: 8,restaurant_id: 10)
    Item.create(name: "Red curry", price: 8,restaurant_id: 10)
Restaurant.create(name: 'ESSEN', cuisine: 'American', location: '100 Broad St, New York, NY 10004', img_url: "ESSEN.jpg")
    Item.create(name: "Chelsea Combo", price: 8,restaurant_id: 11)
    Item.create(name: "Monte Cristo", price: 8,restaurant_id: 11)
    Item.create(name: "Cuban", price: 8,restaurant_id: 11)
Restaurant.create(name: "Sophie's Cuban Cuisine", cuisine: 'Cuban', location: '73 New St, New York, NY 10004', img_url: "Sophie's Cuban Cuisine.jpg")
    Item.create(name: "Shreaded chicken entree", price: 13,restaurant_id: 12)
    Item.create(name: "Baked chicken entree", price: 11,restaurant_id: 12)
    Item.create(name: "Roast Pork entree", price: 13,restaurant_id: 12)
Restaurant.create(name: "Underground Pizza", cuisine: 'Pizza', location: '3 Hanover Sq, New York, NY 10004', img_url: "Underground Pizza.jpg")
    Item.create(name: "Pepperoni Pie", price: 18,restaurant_id: 13)
    Item.create(name: "Meatball Pie", price: 18,restaurant_id: 13)
    Item.create(name: "Mushroom Pie", price: 18,restaurant_id: 13)
Restaurant.create(name: "Kuu Ramen", cuisine: 'Ramen', location: '20 John St, New York, NY 10038', img_url: "Kuu Ramen.jpg")
    Item.create(name: "Kuu Chili", price: 13,restaurant_id: 14)
    Item.create(name: "Okinawa Shio", price: 11,restaurant_id: 14)
    Item.create(name: "Miso Beef", price: 13,restaurant_id: 14)
Restaurant.create(name: "La Parisienne", cuisine: 'French', location: '9 Maiden Ln, New York, NY 10038', img_url: "La Parisienne.jpg")
    Item.create(name: "Sandwich Matin", price: 8,restaurant_id: 15)
    Item.create(name: "Salmon Brioche", price: 9,restaurant_id: 15)
    Item.create(name: "Avocado Toast", price: 9,restaurant_id: 15)
Restaurant.create(name: "Go! Go! Curry!", cuisine: 'Japanese Curry', location: '12 John St, New York, NY 10038', img_url: "Go! Go! Curry!.jpg")
    Item.create(name: "Katsu Curry", price: 8,restaurant_id: 16)
    Item.create(name: "Original Go! Go! Curry", price: 7,restaurant_id: 16)
    Item.create(name: "Home Run Curry", price: 10,restaurant_id: 16)
Restaurant.create(name: "Antica Ristorante", cuisine: 'Italian', location: '8 Stone St, New York, NY 10004', img_url: "Antica Ristorante.jpg")
    Item.create(name: "New York Choice Steak", price: 29,restaurant_id: 17)
    Item.create(name: "Filetto Di Manxo", price: 26,restaurant_id: 17)
    Item.create(name: "Pollo Martini", price: 25,restaurant_id: 17)
Restaurant.create(name: "Inatteso Pizzabar Casano", cuisine: 'Pizza', location: '28 West St, New York, NY 10004', img_url: "Inatteso Pizzabar Casano.jpg")
    Item.create(name: "Margherita", price: 20,restaurant_id: 18)
    Item.create(name: "Bianca", price: 20,restaurant_id: 18)
    Item.create(name: "Parma", price: 24,restaurant_id: 18)
Restaurant.create(name: "Wogies Bar and Grill", cuisine: 'American', location: '44 Trinity Pl, New York, NY 10006', img_url: "Wogies Bar and Grill.jpeg")
    Item.create(name: "Pookie", price: 13,restaurant_id: 19)
    Item.create(name: "Grilled Chicken Sandwich", price: 13,restaurant_id: 19)
    Item.create(name: "Wogies Fries", price: 7,restaurant_id: 19)
